project:
  type: website
  output-dir: docs
  
publish:
  provider: gh-pages
  repo-url: https://github.com/shaylatriant/shaylalovesrivers.git

website:
  title: "Shayla Triantafillou"
  site-url: https://github.com/shaylatriant/shaylalovesrivers.git
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: news.qmd
        text: News
      - href: photos.qmd
        text: Photos
  search:
    location: navbar
    type: overlay
    
  page-footer:
    background: light
    right:
      - icon: github
        href: https://github.com/shaylatriant
      - icon: envelope
        href: mailto:shayla.triantafillou@colostate.edu
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Shayla_Triantafillou
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=Z-eItxUAAAAJ&hl=en&oi=ao
format:
  html:
    theme:
      - sandstone
      - styles.scss
    toc: true

editor: source

collections:
  projects:
    path: "projects"
    default: true
    title: "Projects"

