project:
  type: website

website:
  title: "Shayla Triantafillou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - photos.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

